name: Sync Fork

on:
  schedule:
    - cron: '0 * * * *' # Checks for updates automatically every hour
  workflow_dispatch: # Gives you a manual button to sync whenever you want

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout target repo
        uses: actions/checkout@v4

      - name: Sync upstream changes natively
        run: gh repo sync davidbrownn/YCN -b main
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
